### ISSUE TITLE
issues when specifying KERNEL_URL with repo name different than 'linux'

### ISSUE THREAD

**Issue by nexus166** [drtyhlpr/rpi23-gen-image#102]
Hi, 

As in subject -- if the name of the repo is not 'linux', script fails because it cannot find /usr/src/linux.

I hardcoded /usr/src/linux and forced git clones to <tempdir>/linux.
I'm about to send a pull in case you'd like to have the fix added :smile:

**Comment by drtyhlpr** [comment]
hi nexus166, thanks for providing the patch!

**Comment by drtyhlpr** [comment]
reported and fixed by nexus166
