### ISSUE TITLE
error of .config file not found. Solved

### ISSUE THREAD

**Issue by youxiaojie** [drtyhlpr/rpi23-gen-image#114]
#
# Build and Setup RPi2/3 Kernel
#
+ . bootstrap.d/13-kernel.sh
+ . ./functions.sh
+ [ true = true ]
+ mkdir -p /home/allan/rpi23-gen-image/working/images/buster/build/chroot/usr/src/linux
+ [ -n /home/allan/rpi_linux/linux ]
+ [ -d /home/allan/rpi_linux/linux ]
+ cp -r /home/allan/rpi_linux/linux/COPYING /home/allan/rpi_linux/linux/CREDITS /home/allan/rpi_linux/linux/Documentation /home/allan/rpi_linux/linux/Kbuild /home/allan/rpi_linux/linux/Kconfig /home/allan/rpi_linux/linux/MAINTAINERS /home/allan/rpi_linux/linux/Makefile /home/allan/rpi_linux/linux/Module.symvers /home/allan/rpi_linux/linux/README /home/allan/rpi_linux/linux/System.map /home/allan/rpi_linux/linux/arch /home/allan/rpi_linux/linux/block /home/allan/rpi_linux/linux/built-in.o /home/allan/rpi_linux/linux/certs /home/allan/rpi_linux/linux/crypto /home/allan/rpi_linux/linux/drivers /home/allan/rpi_linux/linux/firmware /home/allan/rpi_linux/linux/fs /home/allan/rpi_linux/linux/include /home/allan/rpi_linux/linux/init /home/allan/rpi_linux/linux/ipc /home/allan/rpi_linux/linux/kernel /home/allan/rpi_linux/linux/lib /home/allan/rpi_linux/linux/mm /home/allan/rpi_linux/linux/modules.builtin /home/allan/rpi_linux/linux/modules.order /home/allan/rpi_linux/linux/net /home/allan/rpi_linux/linux/samples /home/allan/rpi_linux/linux/scripts /home/allan/rpi_linux/linux/security /home/allan/rpi_linux/linux/sound /home/allan/rpi_linux/linux/tools /home/allan/rpi_linux/linux/usr /home/allan/rpi_linux/linux/virt /home/allan/rpi_linux/linux/vmlinux /home/allan/rpi_linux/linux/vmlinux.o /home/allan/rpi23-gen-image/working/images/buster/build/chroot/usr/src/linux
+ [ false = true ]
+ [ 1 = 1 ]
+ [ -r /proc/cpuinfo ]
+ grep -c processor /proc/cpuinfo
+ KERNEL_THREADS=2
+ [ true = false ]
+ [ ! -r /home/allan/rpi23-gen-image/working/images/buster/build/chroot/usr/src/linux/arch/arm/boot/zImage ]
+ [ false = true ]
+ make -C /home/allan/rpi23-gen-image/working/images/buster/build/chroot/usr/src/linux ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- INSTALL_MOD_PATH=../../.. modules_install
make: Entering directory '/home/allan/rpi23-gen-image/working/images/buster/build/chroot/usr/src/linux'
  SHIPPED scripts/kconfig/zconf.tab.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
scripts/kconfig/conf  --silentoldconfig Kconfig
***
*** Configuration file ".config" not found!
***
*** Please run some configurator (e.g. "make oldconfig" or
*** "make menuconfig" or "make xconfig").
***
scripts/kconfig/Makefile:37: recipe for target 'silentoldconfig' failed
make[2]: *** [silentoldconfig] Error 1
Makefile:547: recipe for target 'silentoldconfig' failed
make[1]: *** [silentoldconfig] Error 2
  DEPMOD  4.13.16-v7+
make: Leaving directory '/home/allan/rpi23-gen-image/working/images/buster/build/chroot/usr/src/linux'
+ make -C /home/allan/rpi23-gen-image/working/images/buster/build/chroot/usr/src/linux ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- INSTALL_FW_PATH=../../../lib firmware_install
make: Entering directory '/home/allan/rpi23-gen-image/working/images/buster/build/chroot/usr/src/linux'
scripts/kconfig/conf  --silentoldconfig Kconfig
***
*** Configuration file ".config" not found!
***
*** Please run some configurator (e.g. "make oldconfig" or
*** "make menuconfig" or "make xconfig").
***
scripts/kconfig/Makefile:37: recipe for target 'silentoldconfig' failed
make[2]: *** [silentoldconfig] Error 1
Makefile:547: recipe for target 'silentoldconfig' failed
make[1]: *** [silentoldconfig] Error 2
  IHEX    firmware/acenic/tg1.bin
  INSTALL ...lib/acenic/tg1.bin
...omitted...
  H16TOFW firmware/vicam/firmware.fw
  INSTALL ...lib/vicam/firmware.fw
  INSTALL ...lib/cpia2/stv0672_vp4.bin
  INSTALL ...lib/yam/1200.bin
  INSTALL ...lib/yam/9600.bin
make: Leaving directory '/home/allan/rpi23-gen-image/working/images/buster/build/chroot/usr/src/linux'
+ [ true = true ]
+ [ false = false ]
+ make -C /home/allan/rpi23-gen-image/working/images/buster/build/chroot/usr/src/linux ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- INSTALL_HDR_PATH=../.. headers_install
make: Entering directory '/home/allan/rpi23-gen-image/working/images/buster/build/chroot/usr/src/linux'
  CHK     include/generated/uapi/linux/version.h
  SYSHDR  arch/arm/include/generated/uapi/asm/unistd-common.h
  SYSHDR  arch/arm/include/generated/uapi/asm/unistd-oabi.h
  SYSHDR  arch/arm/include/generated/uapi/asm/unistd-eabi.h
  HOSTCC  scripts/unifdef
  INSTALL include/asm-generic (35 files)
  INSTALL include/drm (25 files)
  ....omitted...  
  INSTALL include/asm (37 files)
make: Leaving directory '/home/allan/rpi23-gen-image/working/images/buster/build/chroot/usr/src/linux'
+ mkdir /home/allan/rpi23-gen-image/working/images/buster/build/chroot/boot/firmware
+ cat /home/allan/rpi23-gen-image/working/images/buster/build/chroot/usr/src/linux/include/config/kernel.release
+ KERNEL_VERSION=4.13.16-v7+
+ install_readonly /home/allan/rpi23-gen-image/working/images/buster/build/chroot/usr/src/linux/.config /home/allan/rpi23-gen-image/working/images/buster/build/chroot/boot/config-4.13.16-v7+
+ install -o root -g root -m 644 /home/allan/rpi23-gen-image/working/images/buster/build/chroot/usr/src/linux/.config /home/allan/rpi23-gen-image/working/images/buster/build/chroot/boot/config-4.13.16-v7+
install: cannot stat '/home/allan/rpi23-gen-image/working/images/buster/build/chroot/usr/src/linux/.config': No such file or directory
+ cleanup
+ set +x
killing processes using mount point ...
removing temporary mount points ...

**Comment by youxiaojie** [comment]
commit here:
https://github.com/drtyhlpr/rpi23-gen-image/pull/113

**Comment by drtyhlpr** [comment]
thanks for the great patch. did not notice that problem during testing @youxiaojie can you please move your changes of the README.md (Add Simplified Chinese Translation) to README-CN.md so I can join your pull request easily.
