### ISSUE TITLE
why not direct git to ${R}/usr/src/linux or uboot or fbturbo ?

### ISSUE THREAD

**Issue by youxiaojie** [drtyhlpr/rpi23-gen-image#117]
I saw you git the source code first to a temp directory and then copy to chroot 
    # Fetch U-Boot sources
    as_nobody git -C "${temp_dir}" clone "${UBOOT_URL}"

    # Copy downloaded U-Boot sources
    mv "${temp_dir}/u-boot" "${R}/tmp/"

  as_nobody git -C "${temp_dir}" clone --depth=1 --branch "${KERNEL_BRANCH}" "${KERNEL_URL}" linux
   fi
    
    # Copy downloaded kernel sources
    cp -r "${temp_dir}/linux/"* "${R}/usr/src/linux/"

why not git to ${R}/usr/src/xxxx directly?

**Comment by drtyhlpr** [comment]
hi youxiaojie ! ... the git command (aka the download) get executed as user nobody (secure style). the download is performed to an tmp dir (and moved later) because the user nobody needs access rights to it.
