### ISSUE TITLE
WLAN Firmware Not available 

### ISSUE THREAD

**Issue by amanharitsh123** [drtyhlpr/rpi23-gen-image#123]
`WLAN_FIRMWARE_URL=${WLAN_FIRMWARE_URL:=https://github.com/RPi-Distro/firmware-nonfree/raw/master/brcm80211/brcm}`

https://github.com/RPi-Distro/firmware-nonfree/raw/master/brcm80211/brcm
The WLAN Firmware link used in the rpigen script is no longer valid .

P.S: Even After changing the link to https://github.com/RPi-Distro/firmware-nonfree/raw/master/brcm , the script crashed because the file brcmfmac43430-sdio.txt is not available in the repo.

**Comment by amanharitsh123** [comment]
i think this issue has been fixed with the commit https://github.com/RPi-Distro/firmware-nonfree/commit/927fa8ebdf5bcfb90944465b40ec4981e01d6015 
@quozl

**Comment by drtyhlpr** [comment]
hi, thanks for the fix! adding ur pull now!
