### ISSUE TITLE
No rule to make target 'firmware_install' when build kernel

### ISSUE THREAD

**Issue by nguyenhungsync** [drtyhlpr/rpi23-gen-image#136]
![capture](https://user-images.githubusercontent.com/29896020/42309509-f0bbfb76-8062-11e8-91cb-169357cd6d76.PNG)
plz help me

**Comment by DIKIIDM** [comment]
I have the same problem

**Comment by nguyenhungsync** [comment]
yeah. i fixed .
Solution : 
From kernel 4.14 , i must change in file /bootstrap.d/13-kernel.sh , line 118 

> make -C "${KERNEL_DIR}" ARCH="${KERNEL_ARCH}" CROSS_COMPILE="${CROSS_COMPILE}" INSTALL_FW_PATH=../../../lib firmware_install

**to**  

>  make -C "${KERNEL_DIR}" ARCH="${KERNEL_ARCH}" CROSS_COMPILE="${CROSS_COMPILE}" INSTALL_FW_PATH=../../../lib

**Comment by drtyhlpr** [comment]
thanks for the report and quick fix. i am low on time. i would fix this to check/grep if the firmware_install target/string exists in the Makefile. I currently dont have a debian or rpi availible dont know when i will find time to fix this.

**Comment by drtyhlpr** [comment]
hi this should be fixed now:

https://github.com/drtyhlpr/rpi23-gen-image/commit/e96075d9ada5e7c209ba96468bbbf12c820ea876

sorry for the delay.
