### ISSUE TITLE
"fatal error: openssl/bio.h: No such file or directory" while trying to compile kernel 4.18 or 4.19

### ISSUE THREAD

**Issue by BrainStone** [drtyhlpr/rpi23-gen-image#151]
Hi @burnbabyburn,

I'm sure you'll be able to help me with that.  
When I try to compile the kernels 4.18 or 4.19, I get the following error.

```
  UPD     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
  LEX     scripts/dtc/dtc-lexer.lex.c
  HOSTCC  scripts/extract-cert
<stdin>:1335:2: warning: #warning syscall rseq not implemented [-Wcpp]
  YACC    scripts/dtc/dtc-parser.tab.h
  YACC    scripts/dtc/dtc-parser.tab.c
scripts/extract-cert.c:21:10: fatal error: openssl/bio.h: No such file or directory
 #include <openssl/bio.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
scripts/Makefile.host:90: recipe for target 'scripts/extract-cert' failed
make[1]: *** [scripts/extract-cert] Error 1
make[1]: *** Waiting for unfinished jobs....
```

What am I missing to compile that?  
I'd be guessing `libssl-dev`. But I'm not sure whether it's missing on the build system or the image.

**Comment by BrainStone** [comment]
Ok. Will restart the CI build as soon as ftp.de.debian is back up. 😂

**Comment by burnbabyburn** [comment]
Another reason using apt-cacher-ng
I didn't notice that until your post 😂

**Comment by burnbabyburn** [comment]
Compiling on Pi takes like what 1-2days? 

So i am using a 'lil vbox getting the job done. With apt-cacher-ng and 2 cpu-cores (on my six year old i5 main maschine) it takes 30-60min for one image i think. 
I did consider TravisCI but it felt like abuse.

**Comment by BrainStone** [comment]
Ah ok. So I'll throw that on my build host then. Would I have to configure anything or will it just work out of the box?

**Comment by burnbabyburn** [comment]
I downloaded virtualbox for windows, debian testing netinstall, installed all mentioned packages in [build-dependencies](https://github.com/burnbabyburn/rpi23-gen-image/tree/test#build-dependencies), than pulled all used [repositorys ](https://github.com/burnbabyburn/rpi23-gen-image/tree/test#build-box)to my maschine

drop in your existing configuration after that and your good to go.

- apt-cacher-ng is caching your *.deb files. 
- git mirrors are local
- Adding `KERNEL_CCACHE` speeds up kernel compilation!

Building your chroot doesn't require any download and is basically just debootstrap,install & unpack packages, build kernel and copy to img-file.

**Comment by BrainStone** [comment]
That fixed it.
