### ISSUE TITLE
Kernel panic

### ISSUE THREAD

**Issue by drtyhlpr** [drtyhlpr/rpi23-gen-image#165]
RPI_MODEL=3
RELEASE=stretch
BUILD_KERNEL=true
ENABLE_CRYPTFS=true
CRYPTFS_PASSWORD=...
ENABLE_VIDEOCORE=false
ENABLE_WIRELESS=true

system boots to kernel panic . needs investigation

**Comment by drtyhlpr** [comment]
even without ENABLE_CRYPTFS=true, CRYPTFS_PASSWORD=... I run into a kernel panic. hm shit @burnbabyburn can you please verify?

**Comment by ad65190** [comment]
I encountered the same issue with model rpi3P and both stretch and buster releases. it involved a bcm module.

**Comment by burnbabyburn** [comment]
> 
> 
> even without ENABLE_CRYPTFS=true, CRYPTFS_PASSWORD=... I run into a kernel panic. hm shit @burnbabyburn can you please verify?

ofc i am

**Comment by drtyhlpr** [comment]
i checked out  c5881a54a4f11dfa9b98c33e0d047515e5576a82 and do some testing now. If it works ill compare/diff the logs.

**Comment by drtyhlpr** [comment]
hm fuck no. even with checkout back to https://github.com/drtyhlpr/rpi23-gen-image/commit/c5881a54a4f11dfa9b98c33e0d047515e5576a82. still kernel panic. well lets I give qemu a try.

**Comment by drtyhlpr** [comment]
kernel,dtb etc. configurations are quite the same no matter if i chose RPI_MODEL 3 or 3P right?

**Comment by burnbabyburn** [comment]
the kernel panic comes from a reverse partition layout on sd card

**Comment by drtyhlpr** [comment]
hm? was it changed?

**Comment by burnbabyburn** [comment]
not on purpose. probably some "fun" from reverting to bin/sh or escaping from shellcheck. i can boot cryptfs builds too, if i correct bootcmd to point to the right partition.

I'll revert the shellcheck changes around ROOT_OFFSET in rpi23-gen-sh and build an new one

**Comment by drtyhlpr** [comment]
hm the generated images look like they have the right disk layout:

```
fdisk -l ..
2048 64M Win95 FA
231345 Linux
```

**Comment by burnbabyburn** [comment]
The following line 
CMDLINE="dwc_otg.lpm_enable=0 root=/dev/mmcblk0p2
needs to be
CMDLINE="dwc_otg.lpm_enable=0 root=/dev/mmcblk0p1
to boot my branch

**Comment by drtyhlpr** [comment]
hm the 1st part should be windows to let the raspberry load and boot .txt files and bins. the root= should be the root partition of the linux partition and linux should be 2nd. hm I just removed the escapes from the shellcheck and currently building the test image

**Comment by burnbabyburn** [comment]
ref+fix branch of mine successfully build

```
SET_ARCH=64
RPI_MODEL=3P
RELEASE=buster
ENABLE_CRYPTFS=true
CRYPTFS_PASSWORD=password
```

**Comment by drtyhlpr** [comment]
hm i will try 64 bit now. for default 32 bit I tested to set root to 1 partition and it did not work

**Comment by drtyhlpr** [comment]
`ENABLE_CONSOLE=false` should fix the current problem

**Comment by burnbabyburn** [comment]
i think it's this line:
# Add serial console support
if [ "$ENABLE_CONSOLE" = true ] ; then
  CMDLINE="${CMDLINE} console=ttyAMA0,115200 kgdboc=ttyAMA0,115200"
fi
after i removed it it from cmdline, my kernel panic was gone.

**Comment by burnbabyburn** [comment]
should be fixed
