### ISSUE TITLE
Build with videocore option

### ISSUE THREAD

**Issue by rcla** [drtyhlpr/rpi23-gen-image#167]
If I try to use:

ENABLE_VIDEOCORE = true

I fail with the error "pusd not found"

It works for me, changing sh to bash in the rpi23-gen-image.sh file

I mean change
#!/bin/sh
to
#!/bin/bash

**Comment by drtyhlpr** [comment]
hi there is a upcoming fix the next pull request. *script was switched temprorary to /bin/bash but meant to stay /bin/sh

**Comment by drtyhlpr** [comment]
should be fixed now. otherwise please reopen
