### ISSUE TITLE
RPI3B+ turn of "offloading" on eth0

### ISSUE THREAD

**Issue by burnbabyburn** [drtyhlpr/rpi23-gen-image#173]
Info:
- https://github.com/sakaki-/rpi3-overlay/blob/master/net-misc/rpi3-ethfix/files/init.d_rpi3-ethfix-2
- https://www.raspberrypi.org/forums/viewtopic.php?p=1324321#p1324321

is there a chance we can use a tool already included in our image? like `ip` ?
ethtool --offload eth0 rx off tx off

**Comment by burnbabyburn** [comment]
i may answer myself
http://man7.org/linux/man-pages/man5/systemd.link.5.html
needs to be implemented

**Comment by drtyhlpr** [comment]
Merged - thanks for the fix!
