### ISSUE TITLE
Overlays missing

### ISSUE THREAD

**Issue by burnbabyburn** [drtyhlpr/rpi23-gen-image#178]
Am i the only one who is missing the overlays under `/boot/overlay`?
I needed to add an `o` to `*.dtb` in `13-kernel.sh ` - after that the overlays are beeing copied
the qemu part in `rpi23-gen-image.sh` would need an `o` too.

i checked with raspian and they also contain `dtbo `instead of `dtb `overlays.
```
 # Copy compiled dtb device tree files
  if [ -d "${KERNEL_DIR}/arch/${KERNEL_ARCH}/boot/dts/overlays" ] ; then
    for dtb in "${KERNEL_DIR}/arch/${KERNEL_ARCH}/boot/dts/overlays/"*.dtbo ; do
      if [ -f "${dtb}" ] ; then
        install_readonly "${dtb}" "${BOOT_DIR}/overlays/"
      fi
    done
```

if you can confirm this issue ill make a pull

**Comment by drtyhlpr** [comment]
hi, I can not verify currently. If I remember right I recently added this if statements. hmmm "make firmware" or something like that was removed from the latest kernel versions if i remember right and the "if overlays" checck was implemented because of that hm but I don't remember more...

**Comment by burnbabyburn** [comment]
files got to /boot/firmware/overlay
maybe they changed the overlay file ending, maybe they didn't :) dtbo is the correct one ;)
