### ISSUE TITLE
dphys-swapfile needs to be integrated properly

### ISSUE THREAD

**Issue by BrainStone** [drtyhlpr/rpi23-gen-image#181]
Hi. So I ran into an issue while downgrading from buster to stretch (for compatibility reasons).

While on buster `dphys-swapfile` didn't take up the entire remaining space on the partition with the swapfile, on stretch it does. I'm guessing this happening because of different versions.

In any case, when the service starts, it causes the small partition to be filled entirely, which in turn causes stuff like keygeneration to fail.

So I propose two things (which both should be implemented imho):

- Integrate the `dphys-swapfile` into the script as an option. It is disabled on the base image and after the root partition has been resized, it gets started and enabled
- Resize the root partion first in `rc.firstboot`. 

And lastly I think spacing the firstboot snippest apart a bit wouldn't hurt. So future things can be added more easily. That's why I was doing that in my first PR about that topic.

If you want these changes, I'll revive my intitial PR, which already does most of this anyways, and make sure there aren't any merge conflicts.

**Comment by drtyhlpr** [comment]
thanks for the fix. good job
