### ISSUE TITLE
build kernel arm64 with QEMU - Can't find default configuration "arch/arm64/configs/vexpress_defconfig

### ISSUE THREAD

**Issue by tswaehn** [drtyhlpr/rpi23-gen-image#196]
It looks like there is no kernel config ```vexpress_defconfig``` for arm64 only for arm32. Is it easy to create the config and derive from arm32?

I am looking at this repo: [https://github.com/raspberrypi/linux](url)

Does anybody have experience on this?

**Comment by burnbabyburn** [comment]
is it not enough to change target architecture from 32 to 64?

**Comment by drtyhlpr** [comment]
should be fixed. please reopen is problem still exists.
