### ISSUE TITLE
broken link on project page

### ISSUE THREAD

**Issue by pdelaage** [drtyhlpr/rpi23-gen-image#199]
On the project page at https://github.com/drtyhlpr/rpi23-gen-image, at the very end of the page, there is a list of very useful "External links and references" : 

The link "RPi3 Wireless interface firmware" is BROKEN.

I think the correct link is:
https://github.com/RPi-Distro/firmware-nonfree/tree/master/brcm

Yours sincerely,
Pierre

**Comment by burnbabyburn** [comment]
Thanks for the info Pierre @pdelaage 

now @drtyhlpr need to merge :) Lets hope he'll be back

**Comment by drtyhlpr** [comment]
hi, sorry for the loooong delay :) thanks for the fix
