### ISSUE TITLE
resuming build from error

### ISSUE THREAD

**Issue by artynet** [drtyhlpr/rpi23-gen-image#201]
is there a way to resume an existing build after the failure of a given step ?

**Comment by tswaehn** [comment]
No. It needs rebuild.

**Comment by drtyhlpr** [comment]
yeah. you can speed up the kernel building stuff "on resume or better rebuild" so KERNELSRC_PREBUILT and similar option might help a bit

**Comment by tswaehn** [comment]
Yes, pre-built Kernel is much faster. Thats for sure! Still all the boostrap jobs and apt-packages need time to configure and consume a lot of time, which right now cannot be resumed.
