### ISSUE TITLE
feat: custom.d firstboot action

### ISSUE THREAD

**Issue by tswaehn** [drtyhlpr/rpi23-gen-image#207]
I was wondering if we could implement a standardized hook for firstboot actions. 

why?:

- actions (ex. enable services) that need to be performed after all the default firstboot is done should be added

suggestions:

- we add by calling predefined script in ./custom.d/firstboot/

this does basically the same as the default firstboot:

> cat files/firstboot/10_after_boot.sh >> "${ETC_DIR}/rc.firstboot"

**Comment by drtyhlpr** [comment]
Hi, feel free to add the stuff that you think is usefull for you and others :)  sounds good!

**Comment by tswaehn** [comment]
@drtyhlpr thanks. I try to not interfere with any design paths :)

**Comment by burnbabyburn** [comment]
Kannst du mir das genauer erklären? Ich wollte das gerade in Code umsetzen und verstehe nicht was du meinst.

**Comment by VonOx** [comment]
Hi

Need this feature too
Just handle firstboot script in custom.d if exist

@burnbabyburn  or @tswaehn , have you made the modification ? If not i will make a PR
