### ISSUE TITLE
UBOOT_ENABLE=true does currently not work with RPi3

### ISSUE THREAD

**Issue by drtyhlpr** [drtyhlpr/rpi23-gen-image#47]
the uboot binaries are generated and configuration / device tree looks fine, rpi3 does not boot and keeps stuck in colorfull screen...

**Comment by drtyhlpr** [comment]
does work now (patch released soon). but serial is not working. hm.

**Comment by gfa** [comment]
you just gave me an excuse to buy another pi 3 :), thank you
