### ISSUE TITLE
Feature Request: Add custom repositories

### ISSUE THREAD

**Issue by mbloos** [drtyhlpr/rpi23-gen-image#54]
Would be nice to add custom repositories to the buildscript so you can add packages from custom repositories

**Comment by drtyhlpr** [comment]
hi. the script should already support that - or I did not get your request right:)

"Debian custom packages, i.e. those not in the debian repositories, can be installed by placing them in the packages directory. They are installed immediately after packages from the repositories are installed. Any dependencies listed in the custom packages will be downloaded automatically from the repositories. Do not list these custom packages in APT_INCLUDES.

Scripts in the custom.d directory will be executed after all other installation is complete but before the image is created."
