### ISSUE TITLE
Wrong defaults for ENABLE_ROOT and ENABLE_ROOT_SSH

### ISSUE THREAD

**Issue by shaardie** [drtyhlpr/rpi23-gen-image#58]
According to the Readme `ENABLE_ROOT` and `ENABLE_ROOT_SSH` should have default `true`, but `rpi23-gen-image.sh` shows:
    
    ENABLE_ROOT=${ENABLE_ROOT:=false}
    ENABLE_ROOT_SSH=${ENABLE_ROOT_SSH:=false}

**Comment by denismosolov** [comment]
Hello, 
I've noticed a similar issue and created a pull request here: https://github.com/drtyhlpr/rpi23-gen-image/pull/55
But I'm not sure what should: README.md or rpi23-gen-image.sh
@shaardie what do you think

**Comment by shaardie** [comment]
I would prefer
ENABLE_ROOT=${ENABLE_ROOT:=true}
ENABLE_ROOT_SSH=${ENABLE_ROOT_SSH:=false}

since these are the defaults in Debian Jessie.

**Comment by drtyhlpr** [comment]
I fixed the readme. I did not change the defaults.
