### ISSUE TITLE
Dependencies missing

### ISSUE THREAD

**Issue by shaardie** [drtyhlpr/rpi23-gen-image#59]
For using the scripts I had to install the following extra dependencies under Debian Jessie:

 * psmisc 
 * build-essential (I guess for gcc and libc6-dev)
 * bc
 * dbus

**Comment by gfa** [comment]
i had to install device-tree-compiler to be able to build the kernel (rpi 3)

**Comment by drtyhlpr** [comment]
thanks for the info will patch soon. sorry for the delay

**Comment by drtyhlpr** [comment]
hm I tested it today. Running Debian jessie from netinstall with only "essential system tools" installed inside vmware.

jessie:
psmisc: should be a jessie default package
build-essential: should not be required
bc -> added with patch
dbus: should be a jessie default package

the "crossbuild-essential-armhf" was removed from jessie and emdedian repo has to be added:
echo "deb http://emdebian.org/tools/debian/ jessie main" > /etc/apt/sources.list.d/crosstools.list
```
sudo -u nobody wget -O - http://emdebian.org/tools/debian/emdebian-toolchain-archive.key | apt-key add -
dpkg --add-architecture armhf
apt-get update
```

ps. 
stretch:
bc -> just added with patch
psmisc -> just added with patch
rest seems to work out of the box. testing running releases soon rpi2 - rpi3

**Comment by drtyhlpr** [comment]
@gfa hi, can you tell me what command lines you used for device tree compilation. are the default ones included in the rpi2/3 kernel sources not working (any more)? or did you have a problem with a specific dev driver?

**Comment by drtyhlpr** [comment]
ah you are using UBOOT. well I tried it some months ago and failed to get the device up and running with it.  (dark/lsdcolor screen on all configuration tries) -> https://github.com/drtyhlpr/rpi23-gen-image/issues/47.

so with using "apt-get install device-tree-compiler" (or adding it to the APT required packages) it was/is working? sorry I don't have any rpi around and will be able to test next weekend.

**Comment by gfa** [comment]
Later down the road I found #47, I removed uboot  from the options and installed device-tree-compiler and the image worked fine 😀

Do you want me to test without uboot if the problem appears again? I didn't test without uboot and without device-tree-compiler

I don't have a pi to test but I can test the image creation


On January 6, 2017 7:32:01 PM GMT+08:00, drtyhlpr <notifications@github.com> wrote:
>ah you are using UBOOT. well I tried it some months ago and failed to
>get the device up and running with it.  (dark/lsdcolor screen on all
>configuration tries) ->
>https://github.com/drtyhlpr/rpi23-gen-image/issues/47.
>
>so with using "apt-get install device-tree-compiler" (or adding it to
>the APT required packages) it was/is working? sorry I don't have any
>rpi around and will be able to test next weekend.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/drtyhlpr/rpi23-gen-image/issues/59#issuecomment-270886591

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by drtyhlpr** [comment]
hehe same here... of course all tests and results from your side would be nice. but I think I am just doing exatly the same on some slower vmware hosts. (building on jessie and stretch - added device-tree-compiler etc.).. hitting the console every 30min and doing other so called work in between :)

what currently worries me the most is: https://github.com/drtyhlpr/rpi23-gen-image/issues/61 - I had this problems before as described and invested alot of time to debug and stuff ... without success. problem automatically solved 1-2 weeks later... maybe I got a RPi3 available next to me on Sunday .

**Comment by drtyhlpr** [comment]
seems fixed. testing with various parameter combinations the next days
