### ISSUE TITLE
Raspbian and Raspberry ?

### ISSUE THREAD

**Issue by supergilbert** [drtyhlpr/rpi23-gen-image#74]
Is there a way to make the project compatible with Raspbian and Raspberry ?
Will Raspbian and Raspberry repository be or already are in the roadmap ?

**Comment by drtyhlpr** [comment]
Hi sorry for the delay. Nope that is not planed. This script was created before the raspbian-lite images were available. I haven't looked in the detailed changes of rasbian etc. but it seem to be quite some work.
