### ISSUE TITLE
ENABLE_CONSOLE=false  and UART pins

### ISSUE THREAD

**Issue by g-vidal** [drtyhlpr/rpi23-gen-image#77]
Hi all,
Maybe a dumb question  but I need the answer please.
If I configure the image with ENABLE_CONSOLE=false, does that mean that the UART pins are disabled.
If yes is it possible to activate them with some changes in the config  files afterwards.
Thanks

**Comment by drtyhlpr** [comment]
hi g-vidal,

ENABLE_CONSOLE=false should not disable the UART pins completly but not "linux tty" is "listening" on these pins if its disabled. if you plan to access devices FROM the rpi u should in general avoid to have a "listening linux tty" on the serial. this is very specify to rpi hardware version and confusing with rpi3 , please search the rpi forums for more info :)

hf
