### ISSUE TITLE
root directory with wrong permissions

### ISSUE THREAD

**Issue by brianmay** [drtyhlpr/rpi23-gen-image#84]
Took me sometime to work out why nothing worked as non-root:

```
root@rpi2-stretch:~# ls -ld /              
drwx------ 21 root root 1024 Nov  3 17:17 /
```

Suspect this might be due to my umask when building (077).

**Comment by petterreinholdtsen** [comment]
This seem to be similar to  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844220 .

**Comment by drtyhlpr** [comment]
hi brain, thanks for your feedback. i will test that soon - looks like a simple bug with a simple fix.
