### ISSUE TITLE
Is building the kernel still necessary for rpi3

### ISSUE THREAD

**Issue by ilmaisin** [drtyhlpr/rpi23-gen-image#93]
I am asking if it is still necessary to build the kernel for running Debian on Raspberry Pi 3? I am not sure if I have missed out something, but AFAIK Debian's stock kernel should support the rpi3 too, as it is based on the mainline 4.9 release.

**Comment by eugulixes** [comment]
According to the [Debian Wiki](https://wiki.debian.org/RaspberryPi3), the RPi 3 support in the original Debian kernel leaves much to be desired. But the problem is in the vanilla kernel rather than Debian.
