### ISSUE TITLE
stuck at rainbow boot screen

### ISSUE THREAD

**Issue by qm78** [drtyhlpr/rpi23-gen-image#96]
Built debian stretch image for my rpi2 and tried JRWR'S weekly images, but I'm stuck on rainbow boot screen. Anybody else having same issues, too?

**Comment by drtyhlpr** [comment]
hi qm78! i have not tried JRWR's images yet. I need to wait some days till i have access to my RPi2 and 3 (hm no rpi at my hand right now). The rainbow screen i had often with strech uboot testing, initramfs testing and outdated or wrong formated settings in the rpi config txt files in /boot.
